apiVersion: v1
kind: Pod
metadata:
  name: configmap-file-demo

spec:
  containers:
    - name: demo
      image: busybox:latest
      command: ["sh", "-c", "sleep 3600"]

      volumeMounts:
        - name: config-volume
          mountPath: /config

  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
