apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo

spec:
  containers:
    - name: demo
      image: busybox:latest
      command: ["sh", "-c", "sleep 3600"]

      envFrom:
        - configMapRef:
            name: app-config
