apiVersion: v1
kind: Pod
metadata:
  name: crash-demo

spec:
  containers:
    - name: demo
      image: busybox:latest
      command:
        - sh
        - -c
        - "echo Starting app; sleep 3600"
