apiVersion: v1
kind: Pod
metadata:
  name: secret-demo

spec:
  containers:
    - name: demo
      image: busybox:latest
      command: ["sh", "-c", "sleep 3600"]

      envFrom:
        - secretRef:
            name: app-secret
